

spring.application.name=cadastro
spring.datasource.url=jdbc:postgresql://localhost:5432/cadastro
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=uma-chave-secreta-bem-grande-para-o-meu-projeto-123456789
api.security.token.expiration=3600000


